// <auto-generated />
using Inn_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inn_Management_System.Migrations
{
    [DbContext(typeof(InnDbContext))]
    [Migration("20220421005740_AddStudentsTable1")]
    partial class AddStudentsTable1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inn_Management_System.Models.Amenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "conditions"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Animals are allowed"
                        },
                        new
                        {
                            ID = 2,
                            Name = "coffee maker"
                        });
                });

            modelBuilder.Entity("Inn_Management_System.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "IRBID",
                            Name = "Inn-IRBID",
                            Phone = "096226521",
                            State = "jordan"
                        },
                        new
                        {
                            ID = 2,
                            Address = "JERASH",
                            Name = "Inn-JERASH",
                            Phone = "096226522",
                            State = "jordan"
                        },
                        new
                        {
                            ID = 3,
                            Address = "UMM QAIS",
                            Name = "Inn-UMM QAIS",
                            Phone = "096226523",
                            State = "jordan"
                        });
                });

            modelBuilder.Entity("Inn_Management_System.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 0,
                            Name = "studio"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 1,
                            Name = "one bedroom"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 2,
                            Name = "2 bedrooms"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
